const data = {
  products: [
    {
      id: 1,
      name: "Nike shirt ",
      category: "shirt",
      image: "/images/p1.jpg",
      price: 3000,
      rating: 4.5,
      numReview: 10,
      discription: "high quality product",
    },
    {
      id: 2,
      name: "Nike shirt 2 ",
      category: "shirt",
      image: "/images/p1.jpg",
      price: 4000,
      rating: 4.3,
      numReview: 30,
      discription: "high quality product",
    },
    {
      id: 3,
      name: "Nike shirt  3",
      category: "shirt",
      image: "/images/p1.jpg",
      price: 1060,
      rating: 3.5,
      numReview: 110,
      discription: "high quality product",
    },
    {
      id: 4,
      name: "Nike shirt 4 ",
      category: "shirt",
      image: "/images/p1.jpg",
      price: 1300,
      rating: 4.15,
      numReview: 102,
      discription: "high quality product",
    },
    {
      id: 5,
      name: "Nike shirt 5",
      category: "shirt",
      image: "/images/p1.jpg",
      price: 1040,
      rating: 4.5,
      numReview: 10,
      discription: "high quality product",
    },
    {
      id: 6,
      name: "Nike shirt 6 ",
      category: "shirt",
      image: "/images/p1.jpg",
      price: 1000,
      rating: 4.5,
      numReview: 10,
      discription: "high quality product",
    },
  ],
};
export default data;
